name: jsirptestsite
favicon: null
layout_spectrum: 0.24119
typography_spectrum: 0.74458
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#858585'
    - '#1e201f'
    - '#f0e610'
    - '#b7b21b'
  brandStrength: 0.3125
  lightness: 0.8048513731919229
  saturation: 0.4401741854380816
  rhythmicContrast: 0.4917285686824471
purpose: []
