name: jsirptestsite
favicon: null
layout_spectrum: 0.24119
typography_spectrum: 0.74458
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.8048513731919229
  saturation: 0.4401741854380816
  rhythmicContrast: 0.4917285686824471
purpose: []
